<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="$(find pai_urdf)/xacro/transmission.xacro" />
    <xacro:macro name="leg" params="name mirror mirror_dae">
        <joint name="${name}_hip_joint" type="revolute">
            <parent link="trunk" />
            <child link="${name}_hip" />
            <dynamics damping="${damping}" friction="${friction}" />
            <xacro:if value="${(mirror_dae == True)}">
                <origin xyz="0.049 -0.075 0.037" rpy="${PI} 0 0" />
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}"
                    lower="${-30*PI/180.0}" upper="${30*PI/180.0}" />
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <origin xyz="0.049 0.075 0.037" rpy="${PI} 0 0" />
                <limit effort="${hip_torque_max}" velocity="${hip_velocity_max}"
                    lower="${-30*PI/180.0}" upper="${30*PI/180.0}" />
            </xacro:if>
            <axis xyz="-1 0 0" />
        </joint>
        <link name="${name}_hip">
            <visual>
                <origin rpy="${0.5*PI} ${PI} 0" xyz="0 0 0" />
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/right-hip-abad.STL" scale="1 1 1" />
                        <!-- <box size="${hip_length*0.001} ${hip_width*0.001} ${hip_height*0.001}" -->
                        <!-- /> -->
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/left-hip-abad.STL" scale="1 1 1" />
                        <!-- <box size="${hip_length*0.001} ${hip_width*0.001} ${hip_height*0.001}"
                        /> -->
                    </geometry>
                </xacro:if>
                <material name="orange" />
            </visual>
            <collision>
                <origin rpy="${0.5*PI} ${PI} 0" xyz="0 1 0" />
                <geometry>
                    <mesh filename="package://pai_urdf/meshes/left-hip-abad.STL" scale="1 1 1"
                    />
                    <!-- <box size="${hip_length*0.001} ${hip_width*0.001} ${hip_height*0.001}" /> -->
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${hip_com_x} ${hip_com_y} ${hip_com_z}" />
                <mass value="${hip_mass}" />
                <inertia
                    ixx="${hip_ixx*0.001*0.001}" ixy="${hip_ixy*0.001*0.001}"
                    ixz="${hip_ixz*0.001*0.001}"
                    iyy="${hip_iyy*0.001*0.001}" iyz="${hip_iyz*0.001*0.001}"
                    izz="${hip_izz*0.001*0.001}" />
            </inertial>
        </link>
        <joint name="${name}_hip2_joint" type="revolute">
            <parent link="${name}_hip" />
            <child link="${name}_hip2" />
            <axis xyz="-1 0 0" />
            <dynamics damping="${damping}" friction="${friction}" />
            <xacro:if value="${(mirror_dae == True)}">
                <origin xyz="0 0 0.0375" rpy="1.5708 -1.5708 0" />
                <limit effort="${hip2_torque_max}" velocity="${hip2_velocity_max}"
                    lower="${-30*PI/180.0}" upper="${30*PI/180.0}" />
            </xacro:if>
            <xacro:if value="${(mirror_dae == False)}">
                <origin xyz="0 0 0.0375" rpy="1.5708 -1.5708 0" />
                <limit effort="${hip2_torque_max}" velocity="${hip2_velocity_max}"
                    lower="${-30*PI/180.0}" upper="${30*PI/180.0}" />
            </xacro:if>
        </joint>
        <link name="${name}_hip2">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/right-hip-yaw.STL" scale="1 1 1" />
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/left-hip-yaw.STL" scale="1 1 1" />
                    </geometry>
                </xacro:if>
                <material name="red" />
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <mesh filename="package://pai_urdf/meshes/left-hip-yaw.STL" scale="1 1 1" />
                </geometry>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="0.05666 0.000508 0.050666" />
                <mass value="${hip2_mass}" />
                <inertia
                    ixx="${hip2_ixx*0.001*0.001}" ixy="${hip2_ixy*0.001*0.001}"
                    ixz="${hip2_ixz*0.001*0.001}"
                    iyy="${hip2_iyy*0.001*0.001}" iyz="${hip2_iyz*0.001*0.001}"
                    izz="${hip2_izz*0.001*0.001}" />
            </inertial>
        </link>
        <joint name="${name}_thigh_joint" type="revolute">
            <xacro:if value="${mirror_dae == True}">
                <origin xyz="0 0 0" rpy="0 0 ${-0.25*PI}" />
                <axis xyz="0 0 -1" />
                <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}"
                    lower="${-0.25*PI}" upper="${0.15*PI}" />
            </xacro:if>
            <xacro:if value="${mirror_dae == False}">
                <origin xyz="0 0 0" rpy="0 0 ${-0.25*PI}" />
                <axis xyz="0 0 1" />
                <limit effort="${thigh_torque_max}" velocity="${thigh_velocity_max}"
                    lower="${-0.15*PI}" upper="${0.25*PI}" />
            </xacro:if>
            <parent link="${name}_hip2" />
            <child link="${name}_thigh" />
            <joint_properties damping="${damping}" friction="${friction}" />

        </joint>
        <link name="${name}_thigh">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/right-hip-pitch.STL" scale="1 1 1" />
                        <!-- <box size="${thigh_length*0.001} ${thigh_width*0.001}
                        ${thigh_height*0.001}" /> -->
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/left-hip-pitch.STL" scale="1 1 1" />
                        <!-- <box size="${thigh_length*0.001} ${thigh_width*0.001}
                        ${thigh_height*0.001}" /> -->
                    </geometry>
                </xacro:if>
                <material name="white" />
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <!-- <box size="${thigh_length*0.001} ${thigh_width*0.001}
                    ${thigh_height*0.001}" /> -->
                    <mesh filename="package://pai_urdf/meshes/left-hip-pitch.STL" scale="1 1 1" />
                </geometry>
                <surface>
                    <contact>
                        <ode>
                            <min_depth>0.001</min_depth>
                        </ode>
                    </contact>
                </surface>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${thigh_com_x} ${thigh_com_y*mirror} ${thigh_com_z}" />
                <mass value="${thigh_mass}" />
                <inertia
                    ixx="${thigh_ixx*0.001*0.001}" ixy="${thigh_ixy*0.001*0.001}"
                    ixz="${thigh_ixz*0.001*0.001}"
                    iyy="${thigh_iyy*0.001*0.001}" iyz="${thigh_iyz*0.001*0.001}"
                    izz="${thigh_izz*0.001*0.001}" />
            </inertial>
        </link>
        <joint name="${name}_calf_joint" type="revolute">
            <parent link="${name}_thigh" />
            <child link="${name}_calf" />
            <xacro:if value="${mirror_dae == True}">
                <origin xyz="0.15 0 0" rpy="0 0 ${0.5*PI}" />
                <axis xyz="0 0 -1" />
            </xacro:if>
            <xacro:if value="${mirror_dae == False}">
                <origin xyz="0.15 0 0" rpy="${PI} 0 ${0.5*PI}" />
                <axis xyz="0 0 1" />
            </xacro:if>
            <joint_properties damping="${damping}" friction="${friction}" />
            <limit effort="${calf_torque_max}" velocity="${calf_velocity_max}" lower="${-0.2*PI}"
                upper="${0.5*PI}" />
        </joint>
        <link name="${name}_calf">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/right-knee.STL" scale="1 1 1" />
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/left-knee.STL" scale="1 1 1" />
                    </geometry>
                </xacro:if>
                <material name="orange" />
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <mesh filename="package://pai_urdf/meshes/right-knee.STL" scale="1 1 1" />
                </geometry>
                <surface>
                    <contact>
                        <ode>
                            <min_depth>0.001</min_depth>
                        </ode>
                    </contact>
                </surface>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${calf_com_x} ${calf_com_y*mirror} ${calf_com_z}" />
                <mass value="${calf_mass}" />
                <inertia
                    ixx="${calf_ixx*0.001*0.001}" ixy="${calf_ixy*0.001*0.001}"
                    ixz="${calf_ixz*0.001*0.001}"
                    iyy="${calf_iyy*0.001*0.001}" iyz="${calf_iyz*0.001*0.001}"
                    izz="${calf_izz*0.001*0.001}" />
            </inertial>
        </link>
        <joint name="${name}_toe_joint" type="revolute">
            <parent link="${name}_calf" />
            <child link="${name}_toe" />
            <xacro:if value="${mirror_dae == True}">
                <origin xyz="0.16 0 0" rpy="0 0 ${-0.25*PI}" />
                <axis xyz="0 0 1" />
            </xacro:if>
            <xacro:if value="${mirror_dae == False}">
                <origin xyz="0.16 0 0" rpy="0 0 ${0.25*PI}" />
                <axis xyz="0 0 -1" />
            </xacro:if>
            <limit effort="${toe_torque_max}" velocity="${toe_velocity_max}" lower="${-0.15*PI}"
                upper="${0.25*PI}" />
            <joint_properties damping="${damping}" friction="${friction}" />

        </joint>
        <link name="${name}_toe">
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <xacro:if value="${(mirror_dae == True)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/right-ankle.STL" scale="1 1 1" />
                    </geometry>
                </xacro:if>
                <xacro:if value="${(mirror_dae == False)}">
                    <geometry>
                        <mesh filename="package://pai_urdf/meshes/left-ankle.STL" scale="1 1 1" />
                    </geometry>
                </xacro:if>
                <material name="red" />
            </visual>
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0" />
                <geometry>
                    <!-- <box size="${toe_length} ${toe_width} ${toe_height}" /> -->
                    <mesh filename="package://pai_urdf/meshes/right-ankle.STL" scale="1 1 1" />
                </geometry>
                <surface>
                    <contact>
                        <ode>
                            <min_depth>0.001</min_depth>
                        </ode>
                    </contact>
                </surface>
            </collision>
            <inertial>
                <origin rpy="0 0 0" xyz="${toe_com_x} ${toe_com_y*mirror} ${toe_com_z}" />
                <mass value="${toe_mass}" />
                <inertia
                    ixx="${toe_ixx*0.001*0.001}" ixy="${toe_ixy*0.001*0.001}"
                    ixz="${toe_ixz*0.001*0.001}"
                    iyy="${toe_iyy*0.001*0.001}" iyz="${toe_iyz*0.001*0.001}"
                    izz="${toe_izz*0.001*0.001}" />
            </inertial>
        </link>
        <xacro:leg_transmission name="${name}" />
    </xacro:macro>
</robot>